<?php
return [
    'access'=>[
        'list-category'=>'category_list',
        'add-category'=>'category_add',
        'edit-category'=>'category_edit',
        'list-menu'=>'menu_list'
    ],
    'access1'=>[
        'list-product'=>'product_list',
        'add-product'=>'product_add',
        'edit-product'=>'product_edit',
        'delete-product'=>'product_delete'
    ],
    'table_module'=>[
        'category',
        'slider',
        'menu',
        'product',
        'setting',
        'user',
        'role',
        'test'
    ],
    'module_childrent'=>[
        'list',
        'add',
        'edit',
        'delete'
    ]
];